apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-fastapi-service
  namespace: golden-path-apps
  labels:
    app: demo-fastapi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-fastapi-service
  template:
    metadata:
      labels:
        app: demo-fastapi-service
    spec:
      containers:
      - name: backend
        # For PoC speed, using a pre-built public image to demonstrate Argo CD sync performance without waiting for CI build times.
        image: hashicorp/http-echo:latest
        imagePullPolicy: IfNotPresent
        args:
        - "-text={\"status\": \"Version 1.0 Live - Golden Path Backend: demo-fastapi-service\"}"
        - "-listen=:8000"
        ports:
        - containerPort: 8000
